### ISSUE TITLE
Does not work with CouchDB v2

### ISSUE THREAD

**Issue by tlvince** [jo/couchdb-configure#15]
With the new clustering features of CouchDB v2, couchdb-configure fails as it expects `_config` to be on the root, whereas it now exists under `/_node/[node]@[host]/_config`.

**Comment by natew** [comment]
+1 on this, just ran into this

**Comment by layanto** [comment]
https://github.com/jo/couchdb-configure/pull/16

**Comment by gabrielmancini** [comment]
+1

**Comment by jo** [comment]
Fixed in 1.6.1
